### PR TITLE
Additional tests for nuget parser and refactored related specs;

### PR DESCRIPTION
**Pull request by timgluz**
I added missing `parse_requested_version(version_label, dependency, product)` to match with other parsers and add additional tests for this function;

Also i refactored deprecated `fact.should` to `expect(fact).to`.

### CODE REVIEW

**Comment by reiz** [comment]
@timgluz Is this done for merging? Or are some more commits coming?

**Comment by timgluz** [comment]
It's should be done for merge/review;

**Comment by reiz** [comment]
@timgluz OK. I just merged it. Now the tests are running. Let's wait for the results.

**Comment by reiz** [comment]
@timgluz looks good https://circleci.com/gh/versioneye/versioneye-core/443.

**Pull request merged**
